# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: helloworld.proto for package 'example.helloworld'

require 'grpc'
require 'helloworld_pb'

module Example
  module Helloworld
    module Helloworld
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'example.helloworld.Helloworld'

        rpc :Call, Request, Response
      end

      Stub = Service.rpc_stub_class
    end
  end
end
