[package]
name = "grpc_practice_rs"
version = "0.1.0"
authors = ["yagince <straitwalk@gmail.com>"]
edition = "2018"

[dependencies]
grpcio = "0.4.4"
protobuf = "2.8.0"
futures = "0.1.28"

[build-dependencies]
protoc-rust-grpc = "0.6.1"